apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  JWT_ALGORITHM: HS256
  LOG_LEVEL: INFO
  DB_PATH: /data/db.json
  AUTH_SERVICE_URL: http://auth:8001
  EVENTS_SERVICE_URL: http://events:8002
  PROJECTS_SERVICE_URL: http://projects:8003
  PARTICIPANTS_SERVICE_URL: http://participants:8004
  NOTIFICATIONS_SERVICE_URL: http://notifications:8005
